// Generated by CoffeeScript 1.10.0
(function() {
  var Check, Type;

  Type = require('./type2');

  Check = (function() {
    function Check() {}

    Check.prototype.check = function(v) {
      return true;
    };

    Check.prototype.equal = function(check) {
      return false;
    };

    Check.prototype.canAssignFrom = function(check) {
      return false;
    };

    return Check;

  })();

}).call(this);
