// Generated by CoffeeScript 1.10.0
(function() {
  var Type;

  Type = require('./type');

  require('./primitive-type');

  require('./any-type');

  require('./array-type');

  require('./property-type');

  require('./object-type');

  require('./oneof-type');

  require('./procedure-type');

  require('./type-trait');

  module.exports = Type;

}).call(this);
