// Generated by CoffeeScript 1.10.0
(function() {
  var Type, parser, util;

  Type = require('./type');

  require('./primitive-type');

  require('./any-type');

  require('./array-type');

  require('./property-type');

  require('./object-type');

  require('./oneof-type');

  require('./procedure-type');

  require('./type-trait');

  require('./json-schema');

  util = require('./util');

  parser = require('./parser');

  util._mixin(Type, {
    Parser: parser,
    parse: function(exps) {
      return parser.parse(exps);
    }
  });

  module.exports = Type;

}).call(this);
