// Generated by CoffeeScript 1.10.0
(function() {
  var ObjectType, PropertyType, Type, errLib, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  util = require('./util');

  errLib = require('./error');

  Type = require('./type');

  PropertyType = require('./property-type');

  ObjectType = (function(superClass) {
    extend(ObjectType, superClass);

    function ObjectType(properties) {
      var j, keys, len, options, prop;
      if (properties == null) {
        properties = [];
      }
      if (!(this instanceof ObjectType)) {
        return new ObjectType(properties);
      }
      ObjectType.__super__.constructor.call(this);
      keys = {};
      for (j = 0, len = properties.length; j < len; j++) {
        prop = properties[j];
        if (!(prop instanceof Type) && prop.typeCategory === 'Property') {
          throw new Error("invalid_property_type: " + prop);
        }
        if (keys.hasOwnProperty(prop.name)) {
          throw new Error("duplicate_key: " + prop);
        }
        keys[prop.name] = prop;
      }
      options = {
        typeID: Type.typeID++,
        properties: properties
      };
      util._mixin(this, options);
    }

    ObjectType.prototype.typeCategory = 'Object';

    ObjectType.prototype.isGeneric = function() {
      var j, len, prop, ref;
      ref = this.properties;
      for (j = 0, len = ref.length; j < len; j++) {
        prop = ref[j];
        if (prop.isGeneric()) {
          return true;
        }
      }
      return false;
    };

    ObjectType.prototype.isComposite = function() {
      return true;
    };

    ObjectType.prototype.build = ObjectType;

    ObjectType.prototype.isa = function(obj) {
      var j, len, prop, ref;
      if (this.outerIsa(obj)) {
        ref = this.properties;
        for (j = 0, len = ref.length; j < len; j++) {
          prop = ref[j];
          if (!prop.isa(obj[prop.name])) {
            return false;
          }
        }
        return true;
      } else {
        return false;
      }
    };

    ObjectType.prototype.outerIsa = function(obj) {
      return obj instanceof Object;
    };

    ObjectType.prototype._convert = function(obj, error, path, isExplicit) {
      var j, len, prop, ref, result;
      result = {};
      ref = this.properties;
      for (j = 0, len = ref.length; j < len; j++) {
        prop = ref[j];
        result[prop.name] = prop._convert(obj[prop.name], path + "/" + prop.name, isExplicit);
      }
      return result;
    };

    ObjectType.prototype.canAssignFrom = function(type) {
      var i, j, len, prop, sorted, sortedB;
      if (type instanceof ObjectType) {
        sorted = this._sortedProperties();
        sortedB = type._sortedProperties();
        if (sortedB.length < sorted.length) {
          false;
        }
        for (i = j = 0, len = sorted.length; j < len; i = ++j) {
          prop = sorted[i];
          if (!prop.canAssignFrom(sortedB[i])) {
            return false;
          }
        }
        return true;
      } else {
        return false;
      }
    };

    ObjectType.prototype.resolve = function(obj, resolver) {
      var key, props, val;
      props = (function() {
        var results;
        results = [];
        for (key in obj) {
          val = obj[key];
          results.push(PropertyType(key, resolver.resolve(val)));
        }
        return results;
      })();
      return ObjectType(props);
    };

    ObjectType.prototype._sortedProperties = function() {
      return [].concat(this.properties).sort(function(a, b) {
        return a.name > b.name;
      });
    };

    ObjectType.prototype.equal = function(type) {
      var i, j, len, prop, sortedA, sortedB;
      if (type instanceof ObjectType) {
        if (this.properties.length !== type.properties.length) {
          return false;
        }
        sortedA = this._sortedProperties();
        sortedB = type._sortedProperties();
        for (i = j = 0, len = sortedA.length; j < len; i = ++j) {
          prop = sortedA[i];
          if (!prop.equal(sortedB[i])) {
            return false;
          }
        }
        return true;
      } else {
        return false;
      }
    };

    ObjectType.prototype._toString = function(env) {
      var prop, props;
      props = (function() {
        var j, len, ref, results;
        ref = this.properties;
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          prop = ref[j];
          results.push(prop._toString(env));
        }
        return results;
      }).call(this);
      return "Object[" + (props.join(',')) + "]";
    };

    return ObjectType;

  })(Type);

  Type.attachType(Object, ObjectType());

  util._mixin(Type, {
    makeObjectType: ObjectType
  });

  module.exports = ObjectType;

}).call(this);
