// Generated by CoffeeScript 1.10.0
(function() {
  var Type, TypeBinder, errLib, util;

  Type = require('./type');

  util = require('./util');

  errLib = require('./error');

  TypeBinder = (function() {
    function TypeBinder() {
      if (!(this instanceof TypeBinder)) {
        return new TypeBinder();
      }
      this.binders = [];
    }

    TypeBinder.prototype.canAssignFrom = function(lhs, rhs) {
      var e, error;
      try {
        this.assignFrom(lhs, rhs);
        return true;
      } catch (error) {
        e = error;
        return false;
      }
    };

    TypeBinder.prototype.canAssignTo = function(lhs, rhs) {
      return this.canAssignFrom(rhs, lhs);
    };

    TypeBinder.prototype.assignFrom = function(lhs, rhs, i) {
      var binder, j, len, ref;
      if (i == null) {
        i = 0;
      }
      ref = this.binders;
      for (j = 0, len = ref.length; j < len; j++) {
        binder = ref[j];
        if (binder.lhs === lhs) {
          if (binder.rhs.canAssignFrom(rhs)) {
            return;
          } else if (rhs.canAssignFrom(binder.rhs)) {
            binder.rhs = rhs;
          } else {
            throw new Error("TypeBinder.cannotRebind at " + i + ": " + lhs + " <- " + rhs);
          }
        } else {
          continue;
        }
        throw new Error("TypeBinder:bindingFailed at " + i + ": " + lhs + " <!= " + rhs);
      }
      return this.binders.push({
        lhs: lhs,
        rhs: rhs
      });
    };

    TypeBinder.prototype.assignTo = function(lhs, rhs, i) {
      if (i == null) {
        i = 0;
      }
      return this.canAssignFrom(rhs, lhs, i);
    };

    return TypeBinder;

  })();

  util._mixin(Type, {
    makeTypeBinder: TypeBinder
  });

  module.exports = TypeBinder;

}).call(this);
